name: Retrain Model

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  retrain-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ya NO se usa DVC
      # - name: Pull dataset from DVC
      #   run: dvc pull data/student_depression.csv.dvc

      - name: Run retrain script
        run: python src/retrain.py
